version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"  # For Sphinx==4.1

sphinx:
   configuration: docs/source/conf.py

formats:
   - pdf

python:
   install:
   - requirements: docs/requirements.txt
